#' @title Generate Route Title and Description Using LLM
#' @description This function takes the statistics generated from
#' `analyse_gpx()` and creates a prompt that can be sent to a large language
#' model (LLM) using the `ellmer` package. The prompt includes a default string
#' of text with the statistics appended to it, asking the LLM to generate a
#' title and description for the GPX route.
#'
#' @param stats A named list of route statistics generated by `analyse_gpx()`.
#' @param platform Character string. This maps onto the `chat_*()` functions
#'   available in the `ellmer` package. (See
#'   <https://ellmer.tidyverse.org/reference/index.html>) Examples include:
#'   - "openai" - for `chat_openai()`
#'   - "azure" - for `chat_azure()`
#'   - "gemini" - for `chat_gemini()`, and so on.
#' @param api_key Character string. The API key for the LLM service.
#' @param model Character string. The model to use for the LLM (e.g.,
#'   "gpt-3.5-turbo").
#' @param prompt Character string. A custom prompt to use for generating the
#'   title and description. If set to NULL (default), the function uses the
#'   default prompt stored in the package.
#' @param ... Additional arguments passed to the `ellmer::chat_completion()`
#'   function.
#'
#' @return A character string containing the response from the LLM, including
#'   the title and description.
#'
#' @details The function constructs a prompt that describes the route based on
#' the provided statistics. It then sends the prompt to the LLM using the
#' `ellmer` package and returns the generated response.
#'
#' @examples
#' \dontrun{
#' gpx_path <- system.file("extdata", "icc_intro_ride.gpx", package = "gpxtoolbox")
#' gpx_path %>%
#'   analyse_gpx(return = "data") %>%
#'   calculate_route_stats() %>%
#'   gen_description(
#'     platform = "azure",
#'     api_key = Sys.getenv("AZURE_OPENAI_API_KEY"),
#'     deployment_id = "gpt-4o-mini"
#'   )
#' }
#'
#' @import ellmer
#' 
#' @export
gen_description <- function(stats, platform, api_key, model, prompt = NULL, ...) {

  # Construct the prompt
  if (is.null(prompt)) {
    path_to_md <- paste0(path.package("gpxtoolbox"), "/desc_prompt.md")
    prompt_md <- suppressWarnings(readLines(path_to_md))
  } else {
    prompt_md <- prompt
  }

  prompt <- paste0(
      prompt_md,
      "\n\n",
      "Please create a title and description using the following details:\n\n",
      "Total Distance: ", stats$total_distance_km, " km\n",
      "Total Elevation Gain: ", stats$total_elevation_gain_m, " m\n",
      "Total Elevation Loss: ", stats$total_elevation_loss_m, " m\n",
      "Maximum Elevation: ", stats$max_elevation_m, " m\n",
      "Minimum Elevation: ", stats$min_elevation_m, " m\n",
      if (!is.null(stats$start_point)) paste0("Start Point: ", stats$start_point, "\n") else "",
      if (!is.null(stats$end_point)) paste0("End Point: ", stats$end_point, "\n") else "",
      if (!is.null(stats$p25_point)) paste0("Point at 25%: ", stats$p25_point, "\n") else "",
      if (!is.null(stats$p50_point)) paste0("Point at 50%: ", stats$p50_point, "\n") else "",
      if (!is.null(stats$p75_point)) paste0("Point at 75%: ", stats$p75_point, "\n") else "",
      "\nPlease provide a title and description that highlights the key features of this route."
    )

  
  # Function to call from ellmer
  fn_ellmer <- paste0("chat_", platform)
  
  # Call function
  chat <- do.call(
    fn_ellmer,
    args = list(
      api_key = api_key,
      ...
    )
  )  
  
  chat$chat(prompt)

}
